databases:
  - name: Clinica
    plan: free
    databaseName: clinica
    user: root

services:
  - type: web
    plan: free
    name: clinicarossi
    runtime: docker
    envVars:
      # Database
      - key: DATABASE_URL
        value: mysql://root:root@127.0.0.1:8889/clinica
      - key: DB_CONNECTION
        value: mysql
      # Laravel
      - key: APP_KEY
        sync: false
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      # Image-specific vars (richarvey/nginx-php-fpm)
      - key: WEBROOT
        value: /var/www/html/public
      - key: RUN_SCRIPTS
        value: 1
      - key: REAL_IP_HEADER
        value: 1
      - key: SKIP_COMPOSER
        value: 1
